version: '3'

services:
  development:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    command: npm run dev
