version: '3.8'

services:
  db:
    image: postgres:15
    container_name: nusantarakita_db
    restart: always
    environment:
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: nusantarakita
      POSTGRES_USER: user
    ports:
      - "5430:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./data/postgres/nusakita.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d nusantarakita"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    container_name: nusantarakita_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:rootpassword@db:5432/nusantarakita?sslmode=disable
      PORT: 8000
    depends_on:
      db:
        condition: service_healthy

  docs:
    build: ./docs
    container_name: nusantarakita_docs
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - api
    volumes:
      - ./docs:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:8000/v2/

volumes:
  db_data:
