version: '3'

services:
  production:
    environment:
      - NODE_ENV=production
    build:
      context: .
      dockerfile: Dockerfile.prod
    expose:
      - '8080'
    ports:
      - '8080:8080'
    command: node dist/index.js
