name: API CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install dependencies
        working-directory: ./api
        run: go mod download

      - name: Build API
        working-directory: ./api
        run: go build -v ./cmd/server

      - name: Run tests
        working-directory: ./api
        run: go test -v ./...
