name: Test Jupyter Notebooks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: testing
      MYSQL_DATABASE: testing
      DATABASE_URL: mysql+mysqlconnector://root:testing@localhost/testing
    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: testing
          MYSQL_DATABASE: testing
          MYSQL_USER: testing
          MYSQL_PASSWORD: testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set Up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.*"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nbformat

      - name: Run Jupyter Notebook tests
        run: |
          for notebook in $(find . -name "*.ipynb"); do
            jupyter nbconvert --to notebook --execute "$notebook" --ExecutePreprocessor.timeout=600
          done